# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CS-course',
                'doc_host': 'https://maya-guizzi.github.io',
                'git_url': 'https://github.com/maya-guizzi/CS-course',
                'lib_path': 'CS_course'},
  'syms': {'CS_course.core': {'CS_course.core.foo': ('core.html#foo', 'CS_course/core.py')}}}
